# Build stage
FROM golang:1.26 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o server ./cmd

# Run stage
FROM gcr.io/distroless/static:nonroot
WORKDIR /app
COPY --from=builder /app/server .
USER nonroot:nonroot
CMD ["/app/server"]
