FROM golang:1.26 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o server ./cmd

FROM alpine:3.19
WORKDIR /app
RUN adduser -D -u 1000 appuser
COPY --from=builder /app/server .
USER appuser
CMD ["./server"]
